language: node_js
os: linux
node_js:
  13.7.0

branches:
  only:
    - master
    - production

install:
  - npm ci

jobs:
  include:
    - stage: test
      if: (branch =~ ^master$|^production$) AND type = pull_request
      script:
        - npm run lint
        - npm run build

    - stage: publish
      if: (branch = production) AND NOT type = pull_request
      script:
        - npm i @zattoo/zploy@1.0.0-beta.5 -g
        - npm run build
        - zploy --gh_token=$GH_TOKEN --npm_token=$NPM_TOKEN
