language: node_js
os: linux
node_js:
  13.7.0

branches:
  only:
    - master
    - production

install:
  - npm ci

jobs:
  include:
    - stage: test
      if: (branch =~ ^master$|^production$) AND type = pull_request
      script:
        - npm run lint
        - npm run build

    - stage: publish
      before_install:
        - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      install:
        - npm ci
        - npm i @zattoo/zploy@1.0.0-rc.0 -g
      script:
        - zploy --gh_token=$GH_TOKEN --npm_token=$NPM_TOKEN
